// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Scheduller is an autogenerated mock type for the Scheduller type
type Scheduller struct {
	mock.Mock
}

// TestScheduller provides a mock function with given fields:
func (_m *Scheduller) TestScheduller() {
	_m.Called()
}

type NewSchedullerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewScheduller creates a new instance of Scheduller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScheduller(t NewSchedullerT) *Scheduller {
	mock := &Scheduller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
