// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewRepository_InterfaceT is an autogenerated mock type for the NewRepository_InterfaceT type
type NewRepository_InterfaceT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewRepository_InterfaceT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewRepository_InterfaceT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewRepository_InterfaceT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewRepository_InterfaceT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewRepository_InterfaceTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewRepository_InterfaceT creates a new instance of NewRepository_InterfaceT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewRepository_InterfaceT(t NewNewRepository_InterfaceTT) *NewRepository_InterfaceT {
	mock := &NewRepository_InterfaceT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
