// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NewSchedullerT is an autogenerated mock type for the NewSchedullerT type
type NewSchedullerT struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *NewSchedullerT) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *NewSchedullerT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *NewSchedullerT) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *NewSchedullerT) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

type NewNewSchedullerTT interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewSchedullerT creates a new instance of NewSchedullerT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewSchedullerT(t NewNewSchedullerTT) *NewSchedullerT {
	mock := &NewSchedullerT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
