// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// RabbitMQ is an autogenerated mock type for the RabbitMQ type
type RabbitMQ struct {
	mock.Mock
}

// RunJobs provides a mock function with given fields: project, task
func (_m *RabbitMQ) RunJobs(project string, task string) {
	_m.Called(project, task)
}

// Worker provides a mock function with given fields: project, task, job
func (_m *RabbitMQ) Worker(project string, task string, job func()) {
	_m.Called(project, task, job)
}

// NewRabbitMQ creates a new instance of RabbitMQ. It also registers a cleanup function to assert the mocks expectations.
func NewRabbitMQ(t testing.TB) *RabbitMQ {
	mock := &RabbitMQ{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
